<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First number_firstNumber</name>
   <tag></tag>
   <elementGuidId>810ae273-1b12-4a67-a209-29e3b6c74edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#firstNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aa59cbc-2671-46d9-ba31-c5e315f12ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29f5f0c8-e9b1-49a2-b77a-dbe61b7af52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstNumber</value>
      <webElementGuid>dd8dcb8e-8798-4581-bc18-07764e2a4c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstNumber</value>
      <webElementGuid>4056beb5-d2af-4a9d-ac8e-b7cc4c1f66fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstNumber&quot;)</value>
      <webElementGuid>4ee10245-05bd-44e9-b6b7-a1a6a62303aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstNumber']</value>
      <webElementGuid>92513dfb-b7fe-4aed-aa07-211fc8cefc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c1fbe9bb-e3dc-4d21-a091-5a911704871a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstNumber' and @name = 'firstNumber']</value>
      <webElementGuid>77f18b61-2f46-4954-9264-b44f5ecc7672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
